apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zuc9ek4gl-java-springboot 
  janus-idp.io/tekton: zuc9ek4gl-java-springboot
  backstage.io/kubernetes-id: zuc9ek4gl-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zuc9ek4gl-java-springboot
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  